### Create 
POST http://localhost:3000/tasks
content-type: application/json

{
    "title": "Title 4",
    "description": "Description"
}

### Get All
GET http://localhost:3000/tasks



### Get One
GET http://localhost:3000/tasks/9bf2db9f-4768-4169-ac58-c4870344698b



### Delete One
DELETE http://localhost:3000/tasks/ca208bdb-95c8-4dd8-b088-a474b38495a5


### Update Task 
PATCH  http://localhost:3000/tasks
content-type: application/json

{
    "id":"9bf2db9f-4768-4169-ac58-c4870344698b",
    "title": "Title 4",
    "description": "Description",
    "status":"In Progress"
    
}



